### ISSUE TITLE
Reason for using Tensorflow

### ISSUE THREAD

**Issue by jeho-lee** [KeondoPark/votenet_tf#1]
Hi. I really enjoyed reading your paper, PointSplit at IPSN 2023. I like how you parallelize the PointNet++ pipeline with GPU and NPU.

But for the VoteNet implementation, why did you choose re-implement the VoteNet using Tensorflow? 
As PointSplit's hardware is Jetson Nano, you might try to convert the original PyTorch VoteNet into the TensorRT model, which is also a TFLite-like accelerated model.

**Comment by KeondoPark** [comment]
Hi jeho
Thank u for your interest.

We could also use pytorch, but we wanted to make use of Coral EdgeTPU,
which is only compatible with tflite.  To convert from pytorch to
tflite(using tools like onnx) did not work very well due to some custom
modules in Votenet.

Thanks
Keondo


2023년 7월 12일 (수) 오전 10:03, Jeho Lee ***@***.***>님이 작성:

**Comment by jeho-lee** [comment]
Thanks for the clarity.
